name: Release CI

on:
  push:
    tags:
      - '**'

jobs:
  build-and-release:
    runs-on: windows-2019
    env:
      boost_version: 1.84.0
      BOOST_ROOT: ${{ github.workspace }}\deps\boost_1_84_0
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure build environment
        shell: bash
        run: |
          cp env.vs2019.bat env.bat
          cd librime
          git fetch origin "refs/tags/*:refs/tags/*"
          echo rime_version="$(git describe --always)" >> $GITHUB_ENV

      # cache boost
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.BOOST_ROOT }}
          key: ${{ runner.os }}-boost-${{ env.boost_version }}

      # install boost if not cached
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ./install_boost.bat
          ./build.bat boost arm64

      # add msbuild to PATH
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Copy Rime files
        run: |
          .\github.install.bat

      - name: Build TypeDuck Release
        id: build_typeduck
        env:
          RELEASE_BUILD: 1
        run: |
          .\build.bat arm64 installer

      - name: Compress Debug Symbols
        shell: pwsh
        run: |
          output\7z.exe a -t7z "./output/archives/debug_symbols.7z" "output/*.pdb" -r

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          title: "TypeDuck for Windows: ${{ github.ref_name }}"
          files: |
            ./output/archives/TypeDuck*.exe
            ./output/archives/debug_symbols.7z
