name: Release CI

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yml

  release:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Get reference name
        run: |
          echo git_ref_name="$(git describe --always)" >> $env:GITHUB_ENV

      - name: Create GitHub release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.git_ref_name }}
          title: "TypeDuck for Windows: ${{ env.git_ref_name }}"
          files: |
            artifact/*
