name: Windows build
on:
  workflow_call:
jobs:
  build:
    runs-on: windows-2022
    env:
      boost_version: 1.83.0
      BOOST_ROOT: ${{ github.workspace }}\deps\boost_1_83_0
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure build environment
        run: |
          copy env.vs2022.bat env.bat
          cd librime
          git fetch origin "refs/tags/*:refs/tags/*"
          echo rime_version="$(git describe --always)" >> $env:GITHUB_ENV

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.BOOST_ROOT }}
          key: ${{ runner.os }}-boost-${{ env.boost_version }}

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: .\install_boost.bat

      - name: Check submodules
        run: git submodule > submodule-status

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            librime
          key: ${{ runner.os }}-deps-${{ hashFiles('submodule-status') }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Copy Rime files
        run: .\github.install.bat

      - name: Build Weasel
        id: build_weasel
        run: |
          .\build.bat weasel hant installer

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            .\output\archives\TypeDuck*.exe
